[package]
name = "ffed_protosat_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rawloader = "0.37.1"
tiff = "0.10"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3.0"
